### PR TITLE
Apply Reverse Scrolling and Enable Drawing Linestring and Polygon Geometry as Geojson

### PR DESCRIPTION
**Pull request by masterjoseph914**
* Reverse Scrolling
   - The map zooms in on scroll up and zooms out on scroll down.

* Draw Linestring and Polygon
   - Adds a condition that enables drawing of Linestring and Polygon in the map.
   - Both geometries can be drawn together as children of mapview.

### CODE REVIEW

**Comment by harrison-denton** [comment]
Could anyone confirm whether this fix works for them on Linux? Definitely have had something working in Windows, though having issues in Linux

**Comment by harrison-denton** [comment]
Can confirm this does work on Linux

**Comment by danieljuschus** [comment]
I've only tried drawing a single LineString with Linux, but that's working!

**Comment by masterjoseph914** [comment]
> Could anyone confirm whether this fix works for them on Linux? Definitely have had something working in Windows, though having issues in Linux

Yep, it works! I've tested it on my Linux (Fedora) and Windows machine. It also works on android.

**Comment by tito** [comment]
Thanks for the PR !

**Pull request merged**
